---
- hosts: localhost
  gather_facts: false
  vars:
    repo_url: "https://github.com/<username>/<repository>.git"
    dest_dir: "/path/to/destination/directory"
  tasks:
    - name: Clone the GitHub repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        
