---
- hosts: localhost
  gather_facts: false
  vars:
    repo_url: "https://github.com/kishoremp009/nso-kimt22-a2.git"
    dest_dir: "/home/kishore"
  tasks:
    - name: Clone the GitHub repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        
