---
- hosts: localhost
  gather_facts: false
  vars:
    repo_url: "https://github.com/kishoremp009/nso-kimt22-a2.git"
    dest_dir: "/home/kishore"
  tasks:
    - name: Clone the GitHub repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
  vars:
    ssh_config_path: "/path/to/ssh_config"
    ssh_key_path: "/path/to/ssh_key"
  tasks:
    - name: Copy SSH configuration file
      copy:
        src: "{{ ssh_config_path }}"
        dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
    - name: Set permissions on SSH key file
      file:
        path: "{{ ssh_key_path }}"
        mode: '0600'
    - name: Add SSH key to agent
      shell: ssh-add {{ ssh_key_path }} 
       
