---
#try 2
- hosts: all
  become: yes
  tasks:
    - name: Update and Upgrade all packages
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
        autoclean: yes

- hosts: HAproxy
  become: yes
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
      notify:
        - Restart HAProxy

    - name: Copy HAProxy config file
      copy:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg.j2
        mode: 0644
      notify:
        - Restart HAProxy

- hosts: webservers
  become: yes
  tasks:
    - name: Install Python3, Pip , Flask , gunicorn
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - python3
        - python3-pip
        - python3-flask
        - gunicorn

    - name: Copy Application to Web Servers
      copy:
        src: devApp.py
        dest: /home/ubuntu/devApp.py
        mode: 0644

    - name: execute the flask-app deployment
      shell: gunicorn -w 2 -D -b 0.0.0.0:80 devApp:app


  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted

